version: "3"
services:
  app:
    build:  ./app
    expose:
      - "5000"
    depends_on:
      - db

  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Abc12345"
      ACCEPT_EULA: "Y"

  proxy:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
